### ISSUE TITLE
Error with db.dataloaders

### ISSUE THREAD

**Issue by atnassar** [Vidhi2014/Liver-Tumor-Segmentation#1]
Hello,
I am getting the below error when I run the following lines:

dls = db.dataloaders(path/'train_images',bs = bs)#, num_workers=0
dls.show_batch()

Error:
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by Vidhi2014** [comment]
Hello @atnassar,

That error could be because of incompatibility between the PyTorch version and the CUDA toolkit version you are using.
I executed the program with PyTorch version=1.10.0 and CUDA toolkit version=10.2.89 and did not face the error you mentioned, so try to run it using these versions or try creating a new python environment and executing it. You can check their respective versions from the jupyter notebook itself using the following lines of code.
`print(torch.__version__)`
`!conda list cudatoolkit`

Please find some references listed below for the issue you mentioned.

- https://forums.developer.nvidia.com/t/runtimeerror-cuda-error-no-kernel-image-is-available-for-execution-on-the-device/182914/2
- https://stackoverflow.com/questions/69968477/runtimeerror-cuda-error-no-kernel-image-is-available-for-execution-on-the-devi
